# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f7aff5cf9329f9cfd62fa4f837b8e2dfee2b5e622159cafbb43cd4dc9331ec9505385ba480d8e5ae04adef952903acdeb336a0d07ec2f71002451648b4c388cf

test:
  secret_key_base: 0b9a4e85ae03c99aee2a979e5d5234c40d351b87b3372be05edef54720a8d1c14588667dd0bfa33ad5a14815c5b98a26bafb4643c4af0564305b680a7f926f47

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
